from soeunasm import M

DEV_BASE_ADDR = 0xFF00

###

UART_SEND = DEV_BASE_ADDR + 0x00
UART_RECV = DEV_BASE_ADDR + 0x02
UART_STATUS = DEV_BASE_ADDR + 0x04
PS2_RECV = DEV_BASE_ADDR + 0x06
LED = DEV_BASE_ADDR + 0x0A
BTN_READ = DEV_BASE_ADDR + 0x0C

JMP_TARGET = DEV_BASE_ADDR + 0x1C
SYSCALL_ENTRY = DEV_BASE_ADDR + 0x1E

CLK_COUNT_0 = DEV_BASE_ADDR + 0x10
CLK_COUNT_1 = DEV_BASE_ADDR + 0x12
CLK_COUNT_2 = DEV_BASE_ADDR + 0x14
CLK_INSTRUCTIONS_0 = DEV_BASE_ADDR + 0x16
CLK_INSTRUCTIONS_1 = DEV_BASE_ADDR + 0x18
CLK_INSTRUCTIONS_2 = DEV_BASE_ADDR + 0x1A

SD_ADDR_0 = DEV_BASE_ADDR + 0x20
SD_ADDR_1 = DEV_BASE_ADDR + 0x22
SD_OUT = DEV_BASE_ADDR + 0x24
SD_IN = DEV_BASE_ADDR + 0x26
SD_ERROR = DEV_BASE_ADDR + 0x28

###

M_UART_SEND = M[UART_SEND]
M_UART_RECV = M[UART_RECV]
M_UART_STATUS = M[UART_STATUS]
M_PS2_RECV = M[PS2_RECV]
M_LED = M[LED]
M_BTN_READ = M[BTN_READ]
M_JMP_TARGET = M[JMP_TARGET]

M_CLK_COUNT_0 = M[CLK_COUNT_0]
M_CLK_COUNT_1 = M[CLK_COUNT_1]
M_CLK_COUNT_2 = M[CLK_COUNT_2]
M_CLK_INSTRUCTIONS_0 = M[CLK_INSTRUCTIONS_0]
M_CLK_INSTRUCTIONS_1 = M[CLK_INSTRUCTIONS_1]
M_CLK_INSTRUCTIONS_2 = M[CLK_INSTRUCTIONS_2]

###

FLAG_UART_RECV_VALID = 0x8000
FLAG_UART_RECV_EMPTY = 0x4000
FLAG_UART_RECV_FULL = 0x2000
MASK_UART_RECV_COUNT = 0x3F00

FLAG_UART_SEND_EMPTY = 0x0040
FLAG_UART_SEND_FULL = 0x0020
MASK_UART_SEND_COUNT = 0x003F

FLAG_PS2_RECV_VALID = 0x8000

FLAG_SD_OUT_HANDSHAKE = 0x0100
FLAG_SD_OUT_READ = 0x0200
FLAG_SD_OUT_WRITE = 0x0400
FLAG_SD_OUT_CONTINUE = 0x0800
FLAG_SD_OUT_RESET = 0x1000
FLAG_SD_OUT_POWER_ON = 0x8000

FLAG_SD_IN_HANDSHAKE = 0x0100
FLAG_SD_IN_BUSY = 0x0200
MASK_SD_IN_STATUS = 0xF800
SHIFT_SD_IN_STATUS = 16 - 5

BIT_SD_OUT_HANDSHAKE = 8
BIT_SD_OUT_READ = 9
BIT_SD_OUT_WRITE = 10
BIT_SD_OUT_CONTINUE = 11
BIT_SD_OUT_RESET = 12
BIT_SD_OUT_POWER_ON = 15

BIT_SD_IN_HANDSHAKE = 8
BIT_SD_IN_BUSY = 9
